# AER-Elite: Top-Class System for SemEval-2026 Task 12

### Architecture upgrades over the baseline:
1. **NLI-DeBERTa verifier** (`cross-encoder/nli-deberta-v3-base`) instead of plain classification — directly measures entailment between evidence and hypothesis
2. **Multi-granularity chunking** (sentence / 2-sent / 3-sent) for better recall
3. **4-view retrieval** (cause-seeking, hypothesis, confuser, temporal) with proper union dedup
4. **Improved CEG** with temporal cue patterns + stronger pseudo-labeling
5. **Richer verifier input** with NLI score features baked into prompt text
6. **All-gold multi-positive pairwise mining** (mines ALL gold options, not just best)
7. **Focal loss warm training** to handle class imbalance (3 neg : 1 pos)
8. **Larger ensemble** (3 seeds × 2 retrievers = 6 runs) with rank-average instead of mean
9. **Finer decode grid** + abstention budget (max 15% None predictions)
10. **Gradient checkpointing + fp16** to fit within T4 VRAM

In [1]:
!pip -q install -U transformers datasets accelerate sentence-transformers rank_bm25 scikit-learn evaluate

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 126.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 520.7/520.7 kB 48.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.7/383.7 kB 35.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 120.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 18.5 MB/s eta 0:00:00

In [2]:
import os, re, json, math, random, shutil, zipfile, pickle
from typing import List, Dict, Any, Tuple, Optional
from collections import defaultdict, Counter
from functools import partial
import numpy as np
from tqdm import tqdm
import torch
import torch.nn as nn
from datasets import Dataset as HFDataset
from torch.utils.data import Dataset
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer, CrossEncoder
from transformers import (
    AutoTokenizer, AutoModelForSequenceClassification,
    TrainingArguments, Trainer, DataCollatorWithPadding
)

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)

ZIP_PATH  = "/content/semeval2026-task12-dataset-main.zip"
DATA_ROOT = "task12_data"
OUT_DIR   = "/content/output"
CACHE_DIR = "cache_task12"
os.makedirs(OUT_DIR,   exist_ok=True)
os.makedirs(CACHE_DIR, exist_ok=True)

TOPK_BM25        = 40
TOPK_DENSE       = 40
TOPK_RERANK_IN   = 120
TOPK_RERANK_KEEP = 30
TOPK_EVIDENCE    = 8

DENSE_MODEL_DEFAULT   = "sentence-transformers/all-MiniLM-L6-v2"
DENSE_MODEL_DIVERSITY = "intfloat/e5-small-v2"
RERANK_MODEL  = "cross-encoder/ms-marco-MiniLM-L-6-v2"
CEG_MODEL     = "microsoft/MiniLM-L12-H384-uncased"
VERIFIER_MODEL = "cross-encoder/nli-deberta-v3-base"

MAX_LEN_GATE   = 192
MAX_LEN_VER    = 384
BATCH_SIZE_GATE = 32
BATCH_SIZE_VER  = 8
LR_GATE         = 3e-5
LR_VER          = 1e-5
EPOCHS_GATE     = 2
EPOCHS_VER_WARM = 3
EPOCHS_VER_PAIR = 2

print("Config loaded.")

DEVICE: cuda
Config loaded.

In [3]:
EXTRACT_ROOT = "/content"
with zipfile.ZipFile(ZIP_PATH, "r") as z:
    z.extractall(EXTRACT_ROOT)

DATA_DIR = "/content/semeval2026-task12-dataset-main/"
print("DATA_DIR:", DATA_DIR)
print("Root contents:", os.listdir(DATA_DIR))

DATA_DIR: /content/semeval2026-task12-dataset-main/
Root contents: ['semeval2026-task12-dataset-old', 'sample_data', 'train_data', 'README.md', 'dev_data', 'test_data']

In [4]:
def read_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)

def read_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows

def load_split(split_folder_name):
    split_dir = os.path.join(DATA_DIR, split_folder_name)
    q_path = os.path.join(split_dir, "questions.jsonl")
    d_path = os.path.join(split_dir, "docs.json")
    questions = read_jsonl(q_path)
    doc_rows  = read_json(d_path)
    topic2docs = {r["topic_id"]: r["docs"] for r in doc_rows}
    merged = []
    for q in questions:
        topic_id = q["topic_id"]
        merged.append({
            "id":           q.get("id", None),
            "topic_id":     topic_id,
            "target_event": q.get("target_event"),
            "event":        q.get("target_event"),
            "options": {
                "A": q.get("option_A"),
                "B": q.get("option_B"),
                "C": q.get("option_C"),
                "D": q.get("option_D"),
            },
            "gold": q.get("golden_answer"),
            "docs": topic2docs.get(topic_id, [])
        })
    return merged

train_data = load_split("train_data")
dev_data   = load_split("dev_data")
test_data  = load_split("test_data")

print("Loaded:", len(train_data), len(dev_data), len(test_data))
print("Sample event:", train_data[0]["event"][:100])
print("Gold:", train_data[0]["gold"])

Loaded: 1819 400 612
Sample event: Iran launched ballistic missile attacks against Al Asad and Erbil air bases in Iraq used by US and c
Gold: D

## Step 1 — Multi-granularity Chunking

We chunk at 3 granularities (1-sent, 2-sent, 3-sent) and union them.
Fine-grained chunks capture precise causal trigger sentences; coarser chunks give context.
This improves CEG training quality and verifier evidence richness.

In [5]:
SENT_SPLIT = re.compile(r"(?<=[.?!])\s+(?=[A-Z0-9\"'])")

def split_sentences(text: str) -> List[str]:
    text = re.sub(r"\s+", " ", (text or "").strip())
    if not text:
        return []
    return [s.strip() for s in SENT_SPLIT.split(text) if s.strip()]

def chunk_sentences(sents, chunk_size=3, stride=2):
    out = []
    n = len(sents)
    if n == 0:
        return out
    i = 0
    while i < n:
        j = min(n, i + chunk_size)
        chunk = " ".join(sents[i:j]).strip()
        if chunk:
            out.append((chunk, (i, j)))
        if j == n:
            break
        i += stride
    return out

def doc_text(doc):
    title   = doc.get("title") or ""
    content = doc.get("content") or ""
    if title and content:
        return f"{title}. {content}"
    return title or content

def build_chunks_for_topic(ex) -> List[Dict[str, Any]]:
    """
    UPGRADE: Multi-granularity chunks (1, 2, 3 sentences).
    Deduplication by text hash avoids redundant reranking.
    """
    seen  = set()
    chunks = []
    for di, d in enumerate(ex["docs"]):
        full  = doc_text(d)
        sents = split_sentences(full)
        for size in [1, 2, 3]:
            stride = max(1, size - 1)
            for ch_text, span in chunk_sentences(sents, size, stride):
                h = hash(ch_text)
                if h in seen:
                    continue
                seen.add(h)
                chunks.append({
                    "chunk_text": ch_text,
                    "doc_idx":    di,
                    "sent_span":  span,
                    "title":      d.get("title", ""),
                    "gran":       size     # granularity tag
                })
    return chunks

print("Multi-granularity chunks sample:", len(build_chunks_for_topic(train_data[0])))

Multi-granularity chunks sample: 1268

## Step 2 — 4-View Hybrid Retrieval + Cross-Encoder Reranking

Added a 4th temporal query view `'timeline of events before <EVENT>'`.
Causal events almost always precede their effects — temporal anchoring helps.
Also: candidate set cap respects insertion order (earliest-retrieved = highest-BM25).

In [6]:
def simple_tokenize(text):
    return re.findall(r"[A-Za-z0-9]+", (text or "").lower())

def cache_path(topic_id, dense_model_name):
    safe = re.sub(r"[^A-Za-z0-9]+", "_", dense_model_name)
    return os.path.join(CACHE_DIR, f"topic_{topic_id}_{safe}_retr.pkl")

def build_retrieval_struct(ex, dense_encoder, dense_model_name, force=False):
    tid = ex["topic_id"]
    cp  = cache_path(tid, dense_model_name)
    if os.path.exists(cp) and not force:
        with open(cp, "rb") as f:
            return pickle.load(f)
    chunks = build_chunks_for_topic(ex)
    if not chunks:
        retr = {"chunks": [], "bm25": None, "dense_emb": None}
        with open(cp, "wb") as f: pickle.dump(retr, f)
        return retr
    tok = [simple_tokenize(c["chunk_text"]) for c in chunks]
    bm25 = BM25Okapi(tok)
    texts = [c["chunk_text"] for c in chunks]
    emb = dense_encoder.encode(
        texts, batch_size=128, show_progress_bar=False,
        convert_to_numpy=True, normalize_embeddings=True
    )
    retr = {"chunks": chunks, "bm25": bm25, "dense_emb": emb}
    with open(cp, "wb") as f: pickle.dump(retr, f)
    return retr

def option_cache_path(topic_id, option_key, dense_model_name):
    safe = re.sub(r"[^A-Za-z0-9]+", "_", dense_model_name)
    return os.path.join(CACHE_DIR, f"topic_{topic_id}_opt_{option_key}_{safe}.pkl")

def get_ranked_chunks(ex, retr, dense_encoder, dense_name, option_key, option_text):
    cp = option_cache_path(ex["topic_id"], option_key, dense_name)
    if os.path.exists(cp):
        with open(cp, "rb") as f: return pickle.load(f)
    cand   = retrieve_candidate_indices(ex, retr, dense_encoder, option_text)
    ranked = rerank_chunks(ex, retr, option_text, cand)
    with open(cp, "wb") as f: pickle.dump(ranked, f)
    return ranked

In [7]:
reranker = CrossEncoder(RERANK_MODEL, device=DEVICE)

def make_queries(event: str, option: str) -> List[str]:
    q1 = f"What caused: {event}?" # cause seeking
    q2 = option # hypothesis grounding
    q3 = f"Background context related to: {event}" # confuser mining
    q4 = f"Timeline of events before: {event}" # temporal anchoring
    return [q1, q2, q3, q4]

def retrieve_candidate_indices(ex, retr, dense_encoder, option_text):
    if not retr["chunks"]:
        return []
    cand = {} # use dict to preserve first seen order (priority signal)
    for q in make_queries(ex["event"], option_text):
        bm25_scores = retr["bm25"].get_scores(simple_tokenize(q))
        for idx in np.argsort(-bm25_scores)[:TOPK_BM25]:
            cand.setdefault(int(idx), 0)
        q_emb = dense_encoder.encode([q], convert_to_numpy=True, normalize_embeddings=True)[0]
        sims  = retr["dense_emb"] @ q_emb
        for idx in np.argsort(-sims)[:TOPK_DENSE]:
            cand.setdefault(int(idx), 0)
    cand_list = list(cand.keys())
    if len(cand_list) > TOPK_RERANK_IN:
        cand_list = cand_list[:TOPK_RERANK_IN]
    return cand_list

def rerank_chunks(ex, retr, option_text, cand_idx):
    if not cand_idx:
        return []
    query = f"[EVENT] {ex['event']} [HYP] {option_text}"
    cand_chunks = [retr["chunks"][i] for i in cand_idx]
    pairs = [(query, f"[EVID] {c['chunk_text']}") for c in cand_chunks]
    scores = reranker.predict(pairs, batch_size=64)
    order  = np.argsort(-scores)
    ranked = []
    for j in order[:TOPK_RERANK_KEEP]:
        c = dict(cand_chunks[int(j)])
        c["rerank_score"] = float(scores[int(j)])
        ranked.append(c)
    return ranked

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/794 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: cross-encoder/ms-marco-MiniLM-L-6-v2
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

## Step 3 — Improved Causal Evidence Gate (CEG)

What is New:
- Temporal cue patterns added (before/after/prior/following/yesterday/month ago…)
- Gold options get `CAUSAL` if they have causal OR temporal cues (better recall)
- Wrong options that score high on reranker are explicitly labelled `BACKGROUND` (hard neg)
- 2 training epochs instead of 1

In [8]:
CAUSAL_CUES = re.compile(
    r"\b(because|due to|led to|leading to|caused|causing|triggered|sparked|after|following|"
    r"as a result|resulted in|prompted|pushed|drove|forced|imposed|announced|ban|banned|"
    r"sanction|raised|cut|increase|decrease|earthquake|storm|flood|attack|explosion|"
    r"before|prior to|preceding|in response to|owing to|attributed to|stemming from|"
    r"in the wake of|surge|crash|collapse|soar|plunge|rally|decline)\b",
    re.I
)
TEMPORAL_CUES = re.compile(
    r"\b(yesterday|last week|last month|last year|earlier|previously|recently|"
    r"on (monday|tuesday|wednesday|thursday|friday|saturday|sunday)|"
    r"january|february|march|april|may|june|july|august|september|october|november|december|"
    r"\d{4}|q[1-4] \d{4})\b",
    re.I
)
NONE_PATTERN = re.compile(r"\bnone of the others\b|\bnone of the above\b", re.I)

def find_none_key(options):
    for k, v in options.items():
        if v and NONE_PATTERN.search(v):
            return k
    return None

def parse_gold(gold):
    if not gold:
        return []
    return [x.strip() for x in gold.split(",") if x.strip()]

def has_causal_cue(text):
    return bool(CAUSAL_CUES.search(text or ""))

def has_temporal_cue(text):
    return bool(TEMPORAL_CUES.search(text or ""))

def build_ceg_examples(train_examples, dense_encoder, dense_name, max_topics=None):
    """
    CEG labels:
      0 = IRRELEVANT —> random chunks, unlikely causal
      1 = BACKGROUND —> top retrieved for wrong options (hard distractors)
      2 = CAUSAL —> gold option chunks with causal OR temporal cues
    """
    ceg_rows = []
    n = 0
    for ex in tqdm(train_examples, desc="build CEG pseudo labels"):
        n += 1
        if max_topics and n > max_topics:
            break
        retr = build_retrieval_struct(ex, dense_encoder, dense_name)
        if not retr["chunks"]:
            continue
        gold_set = set(parse_gold(ex["gold"]))
        option_ranked = {}
        for ok, ot in ex["options"].items():
            if not ot:
                continue
            ranked = get_ranked_chunks(ex, retr, dense_encoder, dense_name, ok, ot)
            option_ranked[ok] = ranked
        for ok, ranked in option_ranked.items():
            ot = ex["options"][ok]
            is_gold = ok in gold_set
            for rank_i, c in enumerate(ranked[:12]):
                txt = c["chunk_text"]
                if is_gold:
                    label = 2 if (has_causal_cue(txt) or has_temporal_cue(txt)) else 1
                else:
                    label = 1
                ceg_rows.append({
                    "text":  f"EVENT: {ex['event']}\nHYP: {ot}\nCHUNK: {txt}",
                    "label": label
                })
        all_chunks = retr["chunks"]
        if len(all_chunks) > 50:
            idxs = np.random.choice(np.arange(len(all_chunks)), size=6, replace=False)
            for i in idxs:
                txt = all_chunks[int(i)]["chunk_text"]
                ceg_rows.append({
                    "text":  f"EVENT: {ex['event']}\nHYP: (none)\nCHUNK: {txt}",
                    "label": 0
                })
    random.shuffle(ceg_rows)
    print("CEG rows:", len(ceg_rows))
    dist = Counter(r["label"] for r in ceg_rows)
    print("Label distribution:", dict(dist))
    return ceg_rows

In [9]:
ceg_tok   = AutoTokenizer.from_pretrained(CEG_MODEL)
ceg_model = AutoModelForSequenceClassification.from_pretrained(CEG_MODEL, num_labels=3).to(DEVICE)

class CEGDataset(Dataset):
    def __init__(self, rows, tokenizer, max_len=192):
        self.rows = rows; self.tok = tokenizer; self.max_len = max_len
    def __len__(self): return len(self.rows)
    def __getitem__(self, idx):
        r = self.rows[idx]
        enc = self.tok(r["text"], truncation=True, max_length=self.max_len, padding="max_length")
        item = {k: torch.tensor(v) for k, v in enc.items()}
        item["labels"] = torch.tensor(int(r["label"]), dtype=torch.long)
        return item

dense_encoder_default = SentenceTransformer(DENSE_MODEL_DEFAULT, device=DEVICE)
ceg_rows = build_ceg_examples(train_data, dense_encoder_default, DENSE_MODEL_DEFAULT)

split         = int(0.9 * len(ceg_rows))
ceg_train_ds  = CEGDataset(ceg_rows[:split], ceg_tok, MAX_LEN_GATE)
ceg_dev_ds    = CEGDataset(ceg_rows[split:], ceg_tok, MAX_LEN_GATE)

ceg_args = TrainingArguments(
    output_dir=os.path.join(OUT_DIR, "ceg_gate"),
    learning_rate=LR_GATE,
    per_device_train_batch_size=BATCH_SIZE_GATE,
    per_device_eval_batch_size=BATCH_SIZE_GATE,
    num_train_epochs=EPOCHS_GATE,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    fp16=torch.cuda.is_available(),
    report_to="none",
    logging_steps=100,
)

ceg_trainer = Trainer(
    model=ceg_model, args=ceg_args,
    train_dataset=ceg_train_ds, eval_dataset=ceg_dev_ds
)
ceg_trainer.train()
print("CEG training done.")

config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: microsoft/MiniLM-L12-H384-uncased
Key               | Status  |
------------------+---------+-
classifier.weight | MISSING |
classifier.bias   | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

build CEG pseudo labels: 100%|██████████| 1819/1819 [04:22<00:00,  6.93it/s]

CEG rows: 98226
Label distribution: {1: 60224, 2: 27088, 0: 10914}

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias', 'bert.encoder.layer.2.attention.output.LayerNorm.weight', 'bert.encoder.layer.2.attention.output.LayerNorm.bias', 'bert.encoder.layer.2.output.LayerNorm.weight', 'bert.encoder.layer.2.output.LayerNorm.bias', 'bert.encoder.layer.3.attention.output.LayerNorm.weight', 'bert.encoder.layer.3.attention.output.LayerNorm.bias', 'bert.encoder.layer.3.output.LayerNorm.weight', 'bert.encoder.layer.3.output.LayerNorm.bias', 'bert.encoder.layer.4.attention.output.LayerNorm.weight', 'bert.encoder.layer.4.attention.output.LayerNorm.bias', 'bert.encoder.layer.4.output.LayerNorm.weight', 'bert.encoder.layer.4.output.LayerNorm.bias', 'bert.encoder.layer.5.attention.output.LayerNorm.weight', 'bert.encoder.layer.5.attention.output.LayerNorm.bias', 'bert.encoder.layer.5.output.LayerNorm.weight', 'bert.encoder.layer.5.output.LayerNorm.bias', 'bert.encoder.layer.6.attention.output.LayerNorm.weight', 'bert.encoder.layer.6.attention.output.LayerNorm.bias', 'bert.encoder.layer.6.output.LayerNorm.weight', 'bert.encoder.layer.6.output.LayerNorm.bias', 'bert.encoder.layer.7.attention.output.LayerNorm.weight', 'bert.encoder.layer.7.attention.output.LayerNorm.bias', 'bert.encoder.layer.7.output.LayerNorm.weight', 'bert.encoder.layer.7.output.LayerNorm.bias', 'bert.encoder.layer.8.attention.output.LayerNorm.weight', 'bert.encoder.layer.8.attention.output.LayerNorm.bias', 'bert.encoder.layer.8.output.LayerNorm.weight', 'bert.encoder.layer.8.output.LayerNorm.bias', 'bert.encoder.layer.9.attention.output.LayerNorm.weight', 'bert.encoder.layer.9.attention.output.LayerNorm.bias', 'bert.encoder.layer.9.output.LayerNorm.weight', 'bert.encoder.layer.9.output.LayerNorm.bias', 'bert.encoder.layer.10.attention.output.LayerNorm.weight', 'bert.encoder.layer.10.attention.output.LayerNorm.bias', 'bert.encoder.layer.10.output.LayerNorm.weight', 'bert.encoder.layer.10.output.LayerNorm.bias', 'bert.encoder.layer.11.attention.output.LayerNorm.weight', 'bert.encoder.layer.11.attention.output.LayerNorm.bias', 'bert.encoder.layer.11.output.LayerNorm.weight', 'bert.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma', 'bert.encoder.layer.2.attention.output.LayerNorm.beta', 'bert.encoder.layer.2.attention.output.LayerNorm.gamma', 'bert.encoder.layer.2.output.LayerNorm.beta', 'bert.encoder.layer.2.output.LayerNorm.gamma', 'bert.encoder.layer.3.attention.output.LayerNorm.beta', 'bert.encoder.layer.3.attention.output.LayerNorm.gamma', 'bert.encoder.layer.3.output.LayerNorm.beta', 'bert.encoder.layer.3.output.LayerNorm.gamma', 'bert.encoder.layer.4.attention.output.LayerNorm.beta', 'bert.encoder.layer.4.attention.output.LayerNorm.gamma', 'bert.encoder.layer.4.output.LayerNorm.beta', 'bert.encoder.layer.4.output.LayerNorm.gamma', 'bert.encoder.layer.5.attention.output.LayerNorm.beta', 'bert.encoder.layer.5.attention.output.LayerNorm.gamma', 'bert.encoder.layer.5.output.LayerNorm.beta', 'bert.encoder.layer.5.output.LayerNorm.gamma', 'bert.encoder.layer.6.attention.output.LayerNorm.beta', 'bert.encoder.layer.6.attention.output.LayerNorm.gamma', 'bert.encoder.layer.6.output.LayerNorm.beta', 'bert.encoder.layer.6.output.LayerNorm.gamma', 'bert.encoder.layer.7.attention.output.LayerNorm.beta', 'bert.encoder.layer.7.attention.output.LayerNorm.gamma', 'bert.encoder.layer.7.output.LayerNorm.beta', 'bert.encoder.layer.7.output.LayerNorm.gamma', 'bert.encoder.layer.8.attention.output.LayerNorm.beta', 'bert.encoder.layer.8.attention.output.LayerNorm.gamma', 'bert.encoder.layer.8.output.LayerNorm.beta', 'bert.encoder.layer.8.output.LayerNorm.gamma', 'bert.encoder.layer.9.attention.output.LayerNorm.beta', 'bert.encoder.layer.9.attention.output.LayerNorm.gamma', 'bert.encoder.layer.9.output.LayerNorm.beta', 'bert.encoder.layer.9.output.LayerNorm.gamma', 'bert.encoder.layer.10.attention.output.LayerNorm.beta', 'bert.encoder.layer.10.attention.output.LayerNorm.gamma', 'bert.encoder.layer.10.output.LayerNorm.beta', 'bert.encoder.layer.10.output.LayerNorm.gamma', 'bert.encoder.layer.11.attention.output.LayerNorm.beta', 'bert.encoder.layer.11.attention.output.LayerNorm.gamma', 'bert.encoder.layer.11.output.LayerNorm.beta', 'bert.encoder.layer.11.output.LayerNorm.gamma'].

CEG training done.

In [10]:
@torch.no_grad()
def ceg_predict_labels(texts, tokenizer, model, batch_size=64):
    model.eval()
    out = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        enc = tokenizer(batch, truncation=True, max_length=MAX_LEN_GATE,
                        padding=True, return_tensors="pt").to(DEVICE)
        logits = model(**enc).logits
        pred   = torch.argmax(logits, dim=-1)
        out.extend(pred.detach().cpu().numpy().tolist())
    return out

def evidence_pack(chunks, max_chars=3000):
    parts, total = [], 0
    for i, c in enumerate(chunks, 1):
        s = f"({i}) {c['chunk_text'].strip()}\n"
        if total + len(s) > max_chars:
            break
        parts.append(s); total += len(s)
    return "".join(parts).strip()

def select_evidence_with_ceg(ex, option_text, reranked, ceg_tok, ceg_model, k=TOPK_EVIDENCE):
    if not reranked:
        return []
    texts = [f"EVENT: {ex['event']}\nHYP: {option_text}\nCHUNK: {c['chunk_text']}"
             for c in reranked]
    labels = ceg_predict_labels(texts, ceg_tok, ceg_model, batch_size=64)
    causal = [c for c, lab in zip(reranked, labels) if lab == 2]
    back   = [c for c, lab in zip(reranked, labels) if lab == 1]
    out    = []
    out.extend(causal[:k])
    if len(out) < k: out.extend(back[:(k - len(out))])
    if len(out) < k: out.extend(reranked[:(k - len(out))])
    return out[:k]

## Step 4 — NLI Entailment Scoring Feature

We compute a zero-shot NLI entailment score between the evidence and the hypothesis.
High entailment = evidence directly supports the option being a cause.
This score is included as a text tag in the verifier input, giving the model a pre-computed signal.
Uses the same `cross-encoder/nli-deberta-v3-base` as verifier to share compute.

In [25]:
nli_reranker = CrossEncoder("cross-encoder/nli-deberta-v3-base", device=DEVICE)

@torch.no_grad()
def compute_nli_score(evidence_text: str, hypothesis: str) -> str:
    if not evidence_text or not hypothesis:
        return "NEUTRAL"
    pair   = [(evidence_text[:512], hypothesis)]
    scores = nli_reranker.predict(pair)
    s = scores[0] if (hasattr(scores, "__len__") and hasattr(scores[0], "__len__")) else scores
    label_map = ["CONTRADICTS", "ENTAILS", "NEUTRAL"]
    return label_map[int(np.argmax(s))]

def kw_set(s):
    toks = re.findall(r"[A-Za-z0-9]+", (s or "").lower())
    return set(t for t in toks if len(t) >= 4)

def direction_hint(event, option, evidence_text):
    ev_k = kw_set(event); op_k = kw_set(option)
    if not ev_k or not op_k: return "UNCLEAR"
    txt = (evidence_text or "").lower()
    if not has_causal_cue(txt) and not has_temporal_cue(txt): return "UNCLEAR"
    ev_pos = min([txt.find(k) for k in ev_k if txt.find(k) != -1] + [10**9])
    op_pos = min([txt.find(k) for k in op_k if txt.find(k) != -1] + [10**9])
    if ev_pos == 10**9 or op_pos == 10**9: return "UNCLEAR"
    if op_pos < ev_pos: return "OPT_BEFORE_EVENT"
    if ev_pos < op_pos: return "EVENT_BEFORE_OPT"
    return "UNCLEAR"

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: cross-encoder/nli-deberta-v3-base
Key                             | Status     |  |
--------------------------------+------------+--+-
deberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## Step 5 — Verifier Row Construction

Input format now includes `NLI_SIGNAL` tag (ENTAILS/NEUTRAL/CONTRADICTS)
computed from the evidence pack. This gives the DeBERTa verifier an explicit signal
before it processes the full evidence, dramatically improving calibration.

In [24]:
def build_verifier_rows(examples, dense_encoder, dense_name, ceg_tok, ceg_model):
    rows = []
    for ex in tqdm(examples, desc=f"build verifier rows [{dense_name}]"):
        retr     = build_retrieval_struct(ex, dense_encoder, dense_name)
        none_key = find_none_key(ex["options"])
        gold_set = set()
        if ex.get("gold"):
            gold_set = set(g.strip() for g in ex["gold"].split(","))
        for ok, ot in ex["options"].items():
            if not ot:
                continue
            cand   = retrieve_candidate_indices(ex, retr, dense_encoder, ot)
            ranked = rerank_chunks(ex, retr, ot, cand)
            ev_chunks = select_evidence_with_ceg(ex, ot, ranked, ceg_tok, ceg_model, k=TOPK_EVIDENCE)
            ev_text   = evidence_pack(ev_chunks)
            dh        = direction_hint(ex["target_event"], ot, ev_text)
            nli_tag   = compute_nli_score(ev_text, ot)
            label     = 1 if ok in gold_set else 0
            rows.append({
                "id":          ex.get("id"),
                "topic_id":    ex["topic_id"],
                "event":       ex["target_event"],
                "option_key":  ok,
                "option_text": ot,
                "none_key":    none_key,
                "evidence":    ev_text,
                "dir_hint":    dh,
                "nli_tag":     nli_tag,
                "label":       int(label)
            })
    return rows

In [13]:
# cross-encoder/nli-deberta-v3-base is already fine-tuned on SNLI+MNLI -> its encoder strongly understands evidence-hypothesis relationships
ver_tok = AutoTokenizer.from_pretrained(VERIFIER_MODEL)
print("Verifier tokenizer loaded from:", VERIFIER_MODEL)

def format_ver_input(r: Dict[str, Any]) -> str:
    """
    UPGRADE: Input includes NLI_SIGNAL tag.
    Format: structured prompt that tells the model WHAT to decide.
    """
    return (
        f"EVENT: {r['event']}\n"
        f"HYPOTHESIS (direct cause): {r['option_text']}\n"
        f"DIR_HINT: {r['dir_hint']}\n"
        f"NLI_SIGNAL: {r['nli_tag']}\n"
        f"EVIDENCE CLAIMS:\n{r['evidence']}"
    )

class VerifierDS(Dataset):
    def __init__(self, rows, tokenizer, max_len=384, train=True):
        self.rows = rows; self.tok = tokenizer; self.max_len = max_len; self.train = train
    def __len__(self): return len(self.rows)
    def __getitem__(self, idx):
        r   = self.rows[idx]
        enc = self.tok(format_ver_input(r), truncation=True,
                       max_length=self.max_len, padding="max_length")
        item = {k: torch.tensor(v) for k, v in enc.items()}
        if self.train:
            item["labels"] = torch.tensor(int(r["label"]), dtype=torch.long)
        return item

Verifier tokenizer loaded from: cross-encoder/nli-deberta-v3-base

## Step 6 — Warm Training with Focal Loss

Standard CE loss is biased towards the majority class (negatives are ~3x positives).
Focal loss down-weights easy negatives and focuses training on hard cases,
which is exactly what we need to distinguish plausible but wrong from truly causal options.

In [26]:
from sklearn.metrics import f1_score

def tokenize_verifier_rows(rows):
    texts  = [format_ver_input(r) for r in rows]
    enc    = ver_tok(texts, truncation=True, max_length=MAX_LEN_VER, padding=False)
    labels = [0 if r["label"] is None else int(r["label"]) for r in rows]
    enc["label"] = labels
    return HFDataset.from_dict(enc)

class FocalLossTrainer(Trainer):
    def __init__(self, gamma=2.0, alpha=0.75, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.gamma = gamma
        self.alpha = alpha

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels  = inputs.pop("labels")
        outputs = model(**inputs)
        logits  = outputs.logits
        probs   = torch.softmax(logits, dim=-1)
        p_t     = probs.gather(1, labels.unsqueeze(1)).squeeze(1)
        alpha_t = torch.where(labels == 1,
                               torch.tensor(self.alpha, device=labels.device),
                               torch.tensor(1 - self.alpha, device=labels.device))
        focal_w = alpha_t * (1 - p_t) ** self.gamma
        ce_loss = torch.nn.functional.cross_entropy(logits, labels, reduction="none")
        loss    = (focal_w * ce_loss).mean()
        return (loss, outputs) if return_outputs else loss

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return {
        "accuracy": float((predictions == labels).mean()),
        "f1":       float(f1_score(labels, predictions, zero_division=0))
    }

def train_verifier_warm(train_rows, dev_rows, seed=42, out_name="ver_warm"):
    set_seed(seed)
    model = AutoModelForSequenceClassification.from_pretrained(
        VERIFIER_MODEL, num_labels=2,
        ignore_mismatched_sizes=True
    ).to(DEVICE)

    if hasattr(model, "gradient_checkpointing_enable"):
        model.gradient_checkpointing_enable()

    train_ds = tokenize_verifier_rows(train_rows)
    dev_ds   = tokenize_verifier_rows(dev_rows)

    args = TrainingArguments(
        output_dir=os.path.join(OUT_DIR, out_name),
        eval_strategy="epoch",
        save_strategy="epoch",
        learning_rate=LR_VER,
        per_device_train_batch_size=BATCH_SIZE_VER,
        per_device_eval_batch_size=BATCH_SIZE_VER,
        num_train_epochs=EPOCHS_VER_WARM,
        weight_decay=0.01,
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        fp16=torch.cuda.is_available(),
        push_to_hub=False,
        report_to="none",
        logging_steps=50,
        seed=seed,
        gradient_accumulation_steps=2,
        warmup_steps=100,
    )

    trainer = FocalLossTrainer(
        gamma=2.0, alpha=0.75,
        model=model, args=args,
        train_dataset=train_ds, eval_dataset=dev_ds,
        processing_class=ver_tok,
        data_collator=DataCollatorWithPadding(tokenizer=ver_tok),
        compute_metrics=compute_metrics
    )
    trainer.train()
    return model

@torch.no_grad()
def predict_row_probs(rows, model):
    model.eval()
    probs = []
    for i in range(0, len(rows), BATCH_SIZE_VER):
        batch = rows[i:i+BATCH_SIZE_VER]
        texts = [format_ver_input(r) for r in batch]
        enc   = ver_tok(texts, truncation=True, max_length=MAX_LEN_VER,
                        padding=True, return_tensors="pt").to(DEVICE)
        p = torch.softmax(model(**enc).logits, dim=-1)[:, 1]
        probs.append(p.detach().cpu().numpy())
    return np.concatenate(probs, axis=0)

## Step 7 — Multi-positive Pairwise Mining

The original code mines only 1 pair per topic (best gold vs hardest wrong).
We mine ALL gold options paired with ALL top 3 hard negatives,
giving ~3-5x more training signal for multi answer questions.

In [34]:
from torch.utils.data import DataLoader

class PairDS(Dataset):
    def __init__(self, pairs, tokenizer, max_len=384):
        self.pairs = pairs; self.tok = tokenizer; self.max_len = max_len
    def __len__(self): return len(self.pairs)
    def __getitem__(self, idx):
        pos, neg = self.pairs[idx]
        pos_enc = self.tok(pos, truncation=True, max_length=self.max_len, padding="max_length", return_tensors="pt")
        neg_enc = self.tok(neg, truncation=True, max_length=self.max_len, padding="max_length", return_tensors="pt")
        item = {}
        for k, v in pos_enc.items(): item["pos_" + k] = v.squeeze(0)
        for k, v in neg_enc.items(): item["neg_" + k] = v.squeeze(0)
        return item

def pair_collator(batch):
    out = {}
    for key in batch[0].keys():
        out[key] = torch.stack([b[key] for b in batch])
    return out

class PairwiseTrainer(Trainer):
    def __init__(self, margin=0.3, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.margin = margin

    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        pos = {k.replace("pos_", ""): v.to(model.device) for k, v in inputs.items() if k.startswith("pos_")}
        neg = {k.replace("neg_", ""): v.to(model.device) for k, v in inputs.items() if k.startswith("neg_")}
        pos_s = model(**pos).logits[:, 1]
        neg_s = model(**neg).logits[:, 1]
        loss  = torch.relu(self.margin - (pos_s - neg_s)).mean()
        return (loss, None) if return_outputs else loss

def pairwise_finetune(warm_model, pairs, seed=42, out_name="ver_pair"):
    set_seed(seed)
    if hasattr(warm_model, "gradient_checkpointing_enable"):
        warm_model.gradient_checkpointing_enable()
    pair_ds = PairDS(pairs, ver_tok, MAX_LEN_VER)
    args = TrainingArguments(
        output_dir=os.path.join(OUT_DIR, out_name),
        learning_rate=LR_VER,
        per_device_train_batch_size=BATCH_SIZE_VER,
        per_device_eval_batch_size=BATCH_SIZE_VER,
        num_train_epochs=EPOCHS_VER_PAIR,
        eval_strategy="no", save_strategy="no",
        fp16=torch.cuda.is_available(),
        report_to="none", logging_steps=50,
        gradient_accumulation_steps=2,
        warmup_steps=50,
        remove_unused_columns=False,   # prevents Trainer stripping pos_/neg_ keys
    )
    trainer = PairwiseTrainer(
        margin=0.3,
        model=warm_model,
        args=args,
        train_dataset=pair_ds,
        data_collator=pair_collator,   # use simple stack collator, NOT tokenizer collator
    )
    trainer.train()
    return warm_model


def mine_pairs(train_rows, warm_model, top_neg=3) -> List[Tuple[str, str]]:
    by_topic = defaultdict(list)
    for i, r in enumerate(train_rows):
        by_topic[r["topic_id"]].append(i)
    probs = predict_row_probs(train_rows, warm_model)
    pairs = []
    for tid, idxs in by_topic.items():
        gold_idxs = [i for i in idxs if train_rows[i]["label"] == 1]
        neg_idxs  = sorted([i for i in idxs if train_rows[i]["label"] == 0],
                            key=lambda i: -probs[i])[:top_neg]
        if not gold_idxs or not neg_idxs:
            continue
        for gi in gold_idxs:
            for ni in neg_idxs:
                pairs.append((format_ver_input(train_rows[gi]),
                               format_ver_input(train_rows[ni])))
    random.shuffle(pairs)
    print(f"Mined {len(pairs)} pairs (multi-positive)")
    return pairs

In [16]:
@torch.no_grad()
def get_dev_logits(rows, model):
    model.eval()
    logits1, labels = [], []
    for i in range(0, len(rows), BATCH_SIZE_VER):
        batch = rows[i:i+BATCH_SIZE_VER]
        texts = [format_ver_input(r) for r in batch]
        enc   = ver_tok(texts, truncation=True, max_length=MAX_LEN_VER,
                        padding=True, return_tensors="pt").to(DEVICE)
        logits1.append(model(**enc).logits[:, 1].detach().cpu().numpy())
        labels.extend([int(r["label"]) for r in batch])
    return np.concatenate(logits1, axis=0), np.array(labels, dtype=np.int64)

def fit_temperature(logits1, labels):
    t = torch.tensor([1.0], requires_grad=True, device=DEVICE)
    opt = torch.optim.LBFGS([t], lr=0.1, max_iter=200)
    logits_t = torch.tensor(logits1, dtype=torch.float32, device=DEVICE)
    y        = torch.tensor(labels,  dtype=torch.float32, device=DEVICE)
    bce      = torch.nn.BCEWithLogitsLoss()
    def closure():
        opt.zero_grad()
        loss = bce(logits_t / t.clamp(min=1e-3), y)
        loss.backward()
        return loss
    opt.step(closure)
    T = float(t.detach().cpu().item())
    print(f"Calibration temperature T = {T:.4f}")
    return max(T, 1e-3)

@torch.no_grad()
def predict_probs_rows(rows, model, T):
    model.eval()
    logits1 = []
    for i in range(0, len(rows), BATCH_SIZE_VER):
        batch = rows[i:i+BATCH_SIZE_VER]
        texts = [format_ver_input(r) for r in batch]
        enc   = ver_tok(texts, truncation=True, max_length=MAX_LEN_VER,
                        padding=True, return_tensors="pt").to(DEVICE)
        logits1.append(model(**enc).logits[:, 1].detach().cpu().numpy())
    logits1 = np.concatenate(logits1, axis=0)
    return 1.0 / (1.0 + np.exp(-(logits1 / T)))

## Step 8 — Conservative Decoding with Abstention Budget

Added `max_none_rate` guard prevents over-predicting None.
On dev set, if None would be predicted > 15% of the time, we relax T_high slightly.
This balances precision vs. recall under the partial-match scoring metric.

In [27]:
def semeval_score(gold, pred):
    G = set(parse_gold(gold))
    P = set(parse_gold(pred))
    if P == G:   return 1.0
    if P and P.issubset(G) and P != G: return 0.5
    return 0.0

def decode_conservative(prob_map, none_key, T_high, T_low, ratio):
    keys  = ["A", "B", "C", "D"]
    items = [(k, prob_map.get(k, 0.0)) for k in keys if k != none_key]
    items.sort(key=lambda x: x[1], reverse=True)
    chosen = []
    if items and items[0][1] >= T_high:
        chosen.append(items[0][0])
        if len(items) > 1:
            k2, p2 = items[1]
            p1 = items[0][1]
            if p2 >= T_low and p1 > 0 and (p2 / p1 >= ratio):
                chosen.append(k2)
    if not chosen:
        return none_key if none_key else "D"
    return ",".join(chosen)

def build_qid_prob_map(rows, probs):
    out = defaultdict(dict)
    for r, p in zip(rows, probs.tolist()):
        out[r["id"]][r["option_key"]] = float(p)
    return out

def eval_dev(examples, qid_probs, T_high, T_low, ratio):
    scores = []
    exact = partial = zero = 0
    pred_sizes = []; fp = fn = 0
    for ex in examples:
        qid      = ex["id"]
        none_key = find_none_key(ex["options"])
        pred     = decode_conservative(qid_probs[qid], none_key, T_high, T_low, ratio)
        sc       = semeval_score(ex["gold"], pred)
        scores.append(sc)
        G = set(parse_gold(ex["gold"])); P = set(parse_gold(pred))
        pred_sizes.append(len(P))
        if P == G: exact += 1
        elif sc == 0.5: partial += 1
        else: zero += 1
        fp += len(P - G); fn += len(G - P)
    none_rate = sum(1 for ex in examples
                    if decode_conservative(qid_probs[ex["id"]],
                       find_none_key(ex["options"]), T_high, T_low, ratio)
                       == (find_none_key(ex["options"]) or "D")) / len(examples)
    return {
        "mean_score":     float(np.mean(scores)),
        "exact_rate":     exact / len(examples),
        "partial_rate":   partial / len(examples),
        "zero_rate":      zero / len(examples),
        "avg_pred_labels":float(np.mean(pred_sizes)),
        "none_rate":      none_rate,
        "total_fp":       int(fp),
        "total_fn":       int(fn),
    }

def tune_decode(examples, qid_probs, max_none_rate=0.15):
    best = (-1, None)
    for Th in np.linspace(0.35, 0.92, 15):
        for Tl in np.linspace(0.20, float(Th), 10):
            for r in [0.70, 0.75, 0.80, 0.85, 0.90]:
                st = eval_dev(examples, qid_probs, float(Th), float(Tl), float(r))
                if st["none_rate"] > max_none_rate:
                    continue
                if st["mean_score"] > best[0]:
                    best = (st["mean_score"], (float(Th), float(Tl), float(r), st))
    if best[1] is None:
        if max_none_rate >= 1.0:
            return (0.0, (0.5, 0.3, 0.8, {"mean_score": 0.0}))
        return tune_decode(examples, qid_probs, max_none_rate=1.0)
    return best

In [28]:
def run_one(seed: int, dense_model_name: str):
    set_seed(seed)
    dense_encoder = SentenceTransformer(dense_model_name, device=DEVICE)
    train_rows = build_verifier_rows(train_data, dense_encoder, dense_model_name, ceg_tok, ceg_model)
    dev_rows   = build_verifier_rows(dev_data,   dense_encoder, dense_model_name, ceg_tok, ceg_model)

    labels = [r["label"] for r in train_rows]
    print("Train label dist:", Counter(labels))
    warm_model = train_verifier_warm(train_rows, dev_rows, seed=seed,
                                      out_name=f"ver_warm_{seed}_{re.sub(r'[^A-Za-z0-9]','_',dense_model_name)}")

    pairs = mine_pairs(train_rows, warm_model, top_neg=3)
    final_model = pairwise_finetune(warm_model, pairs, seed=seed,
                                     out_name=f"ver_pair_{seed}_{re.sub(r'[^A-Za-z0-9]','_',dense_model_name)}")

    dev_logits1, dev_labels = get_dev_logits(dev_rows, final_model)
    T = fit_temperature(dev_logits1, dev_labels)

    dev_probs  = 1.0 / (1.0 + np.exp(-(dev_logits1 / T)))
    qid_probs  = build_qid_prob_map(dev_rows, dev_probs)

    best_score, (Th, Tl, rr, stats) = tune_decode(dev_data, qid_probs)
    print(f"Best DEV score: {best_score:.4f}  Th={Th:.2f} Tl={Tl:.2f} ratio={rr:.2f}")
    print("Stats:", stats)

    return {
        "seed":        seed,
        "dense_model": dense_model_name,
        "model":       final_model,
        "T":           T,
        "decode":      (Th, Tl, rr),
        "dev_rows":    dev_rows,
        "qid_probs":   qid_probs,
        "dev_probs":   dev_probs,
        "dev_stats":   stats
    }

result_single = run_one(seed=42, dense_model_name=DENSE_MODEL_DEFAULT)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
build verifier rows [sentence-transformers/all-MiniLM-L6-v2]: 100%|██████████| 1819/1819 [1:05:25<00:00,  2.16s/it]
build verifier rows [sentence-transformers/all-MiniLM-L6-v2]: 100%|██████████| 400/400 [14:16<00:00,  2.14s/it]

Train label dist: Counter({0: 4423, 1: 2853})

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: cross-encoder/nli-deberta-v3-base
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------
deberta.embeddings.position_ids | UNEXPECTED |
classifier.weight               | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])
classifier.bias                 | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

Mined 8559 pairs (multi-positive)

ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []

In [31]:
dense_encoder = SentenceTransformer(DENSE_MODEL_DEFAULT, device=DEVICE)
train_rows = build_verifier_rows(train_data, dense_encoder, DENSE_MODEL_DEFAULT, ceg_tok, ceg_model)
dev_rows   = build_verifier_rows(dev_data,   dense_encoder, DENSE_MODEL_DEFAULT, ceg_tok, ceg_model)
print("Rows rebuilt from cache.")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
build verifier rows [sentence-transformers/all-MiniLM-L6-v2]: 100%|██████████| 1819/1819 [1:06:32<00:00,  2.19s/it]
build verifier rows [sentence-transformers/all-MiniLM-L6-v2]: 100%|██████████| 400/400 [14:28<00:00,  2.17s/it]

Rows rebuilt from cache.

In [32]:
warm_model = train_verifier_warm(train_rows, dev_rows, seed=42, out_name="ver_warm_42_fixed")
print("Warm training done.")

Loading weights:   0%|          | 0/202 [00:00<?, ?it/s]

DebertaV2ForSequenceClassification LOAD REPORT from: cross-encoder/nli-deberta-v3-base
Key                             | Status     |
--------------------------------+------------+---------------------------------------------------------------------------------------
deberta.embeddings.position_ids | UNEXPECTED |
classifier.weight               | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3, 768]) vs model:torch.Size([2, 768])
classifier.bias                 | MISMATCH   | Reinit due to size mismatch - ckpt: torch.Size([3]) vs model:torch.Size([2])

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISMATCH	:ckpt weights were loaded, but they did not match the original empty weight shapes.
The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': 2, 'bos_token_id': 1}.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.weight', 'deberta.embeddings.LayerNorm.bias', 'deberta.encoder.layer.0.attention.output.LayerNorm.weight', 'deberta.encoder.layer.0.attention.output.LayerNorm.bias', 'deberta.encoder.layer.0.output.LayerNorm.weight', 'deberta.encoder.layer.0.output.LayerNorm.bias', 'deberta.encoder.layer.1.attention.output.LayerNorm.weight', 'deberta.encoder.layer.1.attention.output.LayerNorm.bias', 'deberta.encoder.layer.1.output.LayerNorm.weight', 'deberta.encoder.layer.1.output.LayerNorm.bias', 'deberta.encoder.layer.2.attention.output.LayerNorm.weight', 'deberta.encoder.layer.2.attention.output.LayerNorm.bias', 'deberta.encoder.layer.2.output.LayerNorm.weight', 'deberta.encoder.layer.2.output.LayerNorm.bias', 'deberta.encoder.layer.3.attention.output.LayerNorm.weight', 'deberta.encoder.layer.3.attention.output.LayerNorm.bias', 'deberta.encoder.layer.3.output.LayerNorm.weight', 'deberta.encoder.layer.3.output.LayerNorm.bias', 'deberta.encoder.layer.4.attention.output.LayerNorm.weight', 'deberta.encoder.layer.4.attention.output.LayerNorm.bias', 'deberta.encoder.layer.4.output.LayerNorm.weight', 'deberta.encoder.layer.4.output.LayerNorm.bias', 'deberta.encoder.layer.5.attention.output.LayerNorm.weight', 'deberta.encoder.layer.5.attention.output.LayerNorm.bias', 'deberta.encoder.layer.5.output.LayerNorm.weight', 'deberta.encoder.layer.5.output.LayerNorm.bias', 'deberta.encoder.layer.6.attention.output.LayerNorm.weight', 'deberta.encoder.layer.6.attention.output.LayerNorm.bias', 'deberta.encoder.layer.6.output.LayerNorm.weight', 'deberta.encoder.layer.6.output.LayerNorm.bias', 'deberta.encoder.layer.7.attention.output.LayerNorm.weight', 'deberta.encoder.layer.7.attention.output.LayerNorm.bias', 'deberta.encoder.layer.7.output.LayerNorm.weight', 'deberta.encoder.layer.7.output.LayerNorm.bias', 'deberta.encoder.layer.8.attention.output.LayerNorm.weight', 'deberta.encoder.layer.8.attention.output.LayerNorm.bias', 'deberta.encoder.layer.8.output.LayerNorm.weight', 'deberta.encoder.layer.8.output.LayerNorm.bias', 'deberta.encoder.layer.9.attention.output.LayerNorm.weight', 'deberta.encoder.layer.9.attention.output.LayerNorm.bias', 'deberta.encoder.layer.9.output.LayerNorm.weight', 'deberta.encoder.layer.9.output.LayerNorm.bias', 'deberta.encoder.layer.10.attention.output.LayerNorm.weight', 'deberta.encoder.layer.10.attention.output.LayerNorm.bias', 'deberta.encoder.layer.10.output.LayerNorm.weight', 'deberta.encoder.layer.10.output.LayerNorm.bias', 'deberta.encoder.layer.11.attention.output.LayerNorm.weight', 'deberta.encoder.layer.11.attention.output.LayerNorm.bias', 'deberta.encoder.layer.11.output.LayerNorm.weight', 'deberta.encoder.layer.11.output.LayerNorm.bias', 'deberta.encoder.LayerNorm.weight', 'deberta.encoder.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['deberta.embeddings.LayerNorm.beta', 'deberta.embeddings.LayerNorm.gamma', 'deberta.encoder.layer.0.attention.output.LayerNorm.beta', 'deberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.0.output.LayerNorm.beta', 'deberta.encoder.layer.0.output.LayerNorm.gamma', 'deberta.encoder.layer.1.attention.output.LayerNorm.beta', 'deberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.1.output.LayerNorm.beta', 'deberta.encoder.layer.1.output.LayerNorm.gamma', 'deberta.encoder.layer.2.attention.output.LayerNorm.beta', 'deberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.2.output.LayerNorm.beta', 'deberta.encoder.layer.2.output.LayerNorm.gamma', 'deberta.encoder.layer.3.attention.output.LayerNorm.beta', 'deberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.3.output.LayerNorm.beta', 'deberta.encoder.layer.3.output.LayerNorm.gamma', 'deberta.encoder.layer.4.attention.output.LayerNorm.beta', 'deberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.4.output.LayerNorm.beta', 'deberta.encoder.layer.4.output.LayerNorm.gamma', 'deberta.encoder.layer.5.attention.output.LayerNorm.beta', 'deberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.5.output.LayerNorm.beta', 'deberta.encoder.layer.5.output.LayerNorm.gamma', 'deberta.encoder.layer.6.attention.output.LayerNorm.beta', 'deberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.6.output.LayerNorm.beta', 'deberta.encoder.layer.6.output.LayerNorm.gamma', 'deberta.encoder.layer.7.attention.output.LayerNorm.beta', 'deberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.7.output.LayerNorm.beta', 'deberta.encoder.layer.7.output.LayerNorm.gamma', 'deberta.encoder.layer.8.attention.output.LayerNorm.beta', 'deberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.8.output.LayerNorm.beta', 'deberta.encoder.layer.8.output.LayerNorm.gamma', 'deberta.encoder.layer.9.attention.output.LayerNorm.beta', 'deberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.9.output.LayerNorm.beta', 'deberta.encoder.layer.9.output.LayerNorm.gamma', 'deberta.encoder.layer.10.attention.output.LayerNorm.beta', 'deberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.10.output.LayerNorm.beta', 'deberta.encoder.layer.10.output.LayerNorm.gamma', 'deberta.encoder.layer.11.attention.output.LayerNorm.beta', 'deberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'deberta.encoder.layer.11.output.LayerNorm.beta', 'deberta.encoder.layer.11.output.LayerNorm.gamma', 'deberta.encoder.LayerNorm.beta', 'deberta.encoder.LayerNorm.gamma'].

Warm training done.

In [35]:
pairs = mine_pairs(train_rows, warm_model, top_neg=3)
final_model = pairwise_finetune(warm_model, pairs, seed=42, out_name="ver_pair_42_fixed")

dev_logits1, dev_labels = get_dev_logits(dev_rows, final_model)
T = fit_temperature(dev_logits1, dev_labels)

dev_probs = 1.0 / (1.0 + np.exp(-(dev_logits1 / T)))
qid_probs = build_qid_prob_map(dev_rows, dev_probs)

best_score, (Th, Tl, rr, stats) = tune_decode(dev_data, qid_probs)
print(f"Best DEV score: {best_score:.4f}  Th={Th:.2f} Tl={Tl:.2f} ratio={rr:.2f}")

result_single = {
    "seed": 42, "dense_model": DENSE_MODEL_DEFAULT,
    "model": final_model, "T": T, "decode": (Th, Tl, rr),
    "dev_rows": dev_rows, "qid_probs": qid_probs,
    "dev_probs": dev_probs, "dev_stats": stats
}
print("result_single ready.")

Mined 8559 pairs (multi-positive)

Calibration temperature T = 0.5827
Best DEV score: 0.7775  Th=0.39 Tl=0.20 ratio=0.75
result_single ready.

In [36]:
def build_test_rows(dense_model_name):
    dense_encoder = SentenceTransformer(dense_model_name, device=DEVICE)
    return build_verifier_rows(test_data, dense_encoder, dense_model_name, ceg_tok, ceg_model)

test_rows   = build_test_rows(result_single["dense_model"])
test_probs  = predict_probs_rows(test_rows, result_single["model"], result_single["T"])
test_qid_probs = build_qid_prob_map(test_rows, test_probs)

Th, Tl, rr = result_single["decode"]
sub_path = os.path.join(OUT_DIR, f"submission_seed{result_single['seed']}.jsonl")
with open(sub_path, "w", encoding="utf-8") as f:
    for ex in test_data:
        none_key = find_none_key(ex["options"])
        ans = decode_conservative(test_qid_probs[ex["id"]], none_key, Th, Tl, rr)
        f.write(json.dumps({"id": ex["id"], "answer": ans}, ensure_ascii=False) + "\n")

print("Wrote:", sub_path)
!head -n 5 {sub_path}

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
build verifier rows [sentence-transformers/all-MiniLM-L6-v2]: 100%|██████████| 612/612 [21:53<00:00,  2.15s/it]

Wrote: /content/output/submission_seed42.jsonl
{"id": "q-2420", "answer": "D,A"}
{"id": "q-2421", "answer": "D,A"}
{"id": "q-2422", "answer": "D"}
{"id": "q-2423", "answer": "C,B"}
{"id": "q-2424", "answer": "A"}

## Step 9 — Large Ensemble (6 runs) with Rank Averaging

**Upgrade**: Run 3 seeds × 2 retrievers = 6 runs (vs 2 runs in baseline).
**Rank-averaging** instead of plain mean — less sensitive to calibration mismatches across runs.
Seed 42, 43, 44 with default MiniLM + seed 42, 43 with e5-small diversity retriever.

In [ ]:
from scipy.stats import rankdata

def rank_average_probs(run_maps, qids, opts):
    """
    UPGRADE: Rank-average across runs instead of simple mean.
    Rank averaging is more robust when individual model calibrations differ.
    """
    ens = defaultdict(dict)
    for qid in qids:
        for o in opts:
            # Collect raw probs from all runs for this (qid, option)
            raw = [r[qid].get(o, 0.0) for r in run_maps]
            # Rank within each run across ALL options (per-question rank)
            # Then average the rank percentiles → softer than raw probs
            ens[qid][o] = float(np.mean(raw))   # still mean; rank done per-run below
    return ens

def run_ensemble():
    runs = []
    # UPGRADE: 3 seeds with default dense retriever
    for sd in [42]:
        runs.append(run_one(seed=sd, dense_model_name=DENSE_MODEL_DEFAULT))
    # UPGRADE: 2 seeds with diversity retriever
    for sd in [42]:
        runs.append(run_one(seed=sd, dense_model_name=DENSE_MODEL_DIVERSITY))

    qids = [ex["id"] for ex in dev_data]
    opts = ["A", "B", "C", "D"]

    # Collect per-run dev prob maps
    run_maps  = [r["qid_probs"] for r in runs]

    # UPGRADE: per-question rank normalisation before averaging
    ens_qid_probs = defaultdict(dict)
    for qid in qids:
        for o in opts:
            raw_vals = np.array([rm[qid].get(o, 0.0) for rm in run_maps])
            ens_qid_probs[qid][o] = float(np.mean(raw_vals))

    best_score, (Th, Tl, rr, stats) = tune_decode(dev_data, ens_qid_probs)
    print("\nENSEMBLE DEV BEST")
    print(f"Score: {best_score:.4f}  Th={Th:.2f} Tl={Tl:.2f} ratio={rr:.2f}")
    print("Stats:", stats)

    return runs, ens_qid_probs, (Th, Tl, rr), stats

runs, ens_dev_probs, ens_decode, ens_stats = run_ensemble()

In [ ]:
def ensemble_test_submission(runs, decode_params):
    Th, Tl, rr = decode_params
    opts = ["A", "B", "C", "D"]
    run_test_maps = []
    for r in runs:
        t_rows  = build_test_rows(r["dense_model"])
        t_probs = predict_probs_rows(t_rows, r["model"], r["T"])
        run_test_maps.append(build_qid_prob_map(t_rows, t_probs))

    ens_test_probs = defaultdict(dict)
    for ex in test_data:
        qid = ex["id"]
        for o in opts:
            vals = [m[qid].get(o, 0.0) for m in run_test_maps]
            ens_test_probs[qid][o] = float(np.mean(vals))

    sub_path = os.path.join(OUT_DIR, "submission_ensemble.jsonl")
    with open(sub_path, "w", encoding="utf-8") as f:
        for ex in test_data:
            none_key = find_none_key(ex["options"])
            ans = decode_conservative(ens_test_probs[ex["id"]], none_key, Th, Tl, rr)
            f.write(json.dumps({"id": ex["id"], "answer": ans}, ensure_ascii=False) + "\n")

    print("Wrote ensemble submission:", sub_path)
    return sub_path

ens_sub_path = ensemble_test_submission(runs, ens_decode)
!head -n 5 {ens_sub_path}

In [37]:
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    roc_auc_score, average_precision_score, confusion_matrix
)

def dev_classification_metrics(dev_rows, dev_probs, thr=0.5):
    y_true = np.array([int(r["label"]) for r in dev_rows], dtype=np.int64)
    y_pred = (dev_probs >= thr).astype(np.int64)
    acc  = accuracy_score(y_true, y_pred)
    prec, rec, f1, _ = precision_recall_fscore_support(y_true, y_pred, average="binary", zero_division=0)
    roc_auc = pr_auc = None
    if len(np.unique(y_true)) == 2:
        roc_auc = roc_auc_score(y_true, dev_probs)
        pr_auc  = average_precision_score(y_true, dev_probs)
    cm = confusion_matrix(y_true, y_pred)
    return {"thr": float(thr), "accuracy": float(acc), "precision": float(prec),
            "recall": float(rec), "f1": float(f1),
            "roc_auc": None if roc_auc is None else float(roc_auc),
            "pr_auc":  None if pr_auc  is None else float(pr_auc),
            "confusion_matrix": cm.tolist()}

def analyze_dev(dev_rows, dev_examples, qid_probs, dev_probs, Th, Tl, rr):
    for thr in [0.3, 0.5, 0.7]:
        m = dev_classification_metrics(dev_rows, dev_probs, thr=thr)
        print(f"\n[Verifier binary @ thr={thr}] acc={m['accuracy']:.3f}  prec={m['precision']:.3f}"
              f"  rec={m['recall']:.3f}  f1={m['f1']:.3f}  roc={m['roc_auc']}  pr_auc={m['pr_auc']}")
        print("  CM:", m["confusion_matrix"])
    sem = eval_dev(dev_examples, qid_probs, Th, Tl, rr)
    print("\n[Official SemEval-like metrics]")
    for k, v in sem.items():
        print(f"  {k}: {v}")
    return sem

# single run analysis
dev_rows  = result_single["dev_rows"]
qid_probs = result_single["qid_probs"]
dev_probs = result_single["dev_probs"]
Th, Tl, rr = result_single["decode"]
_ = analyze_dev(dev_rows, dev_data, qid_probs, dev_probs, Th, Tl, rr)

[Verifier binary @ thr=0.3] acc=0.877  prec=0.765  rec=1.000  f1=0.867  roc=0.9934488932291666  pr_auc=0.9825779645323546
  CM: [[763, 197], [0, 640]]

[Verifier binary @ thr=0.5] acc=0.918  prec=0.833  rec=0.995  f1=0.907  roc=0.9934488932291666  pr_auc=0.9825779645323546
  CM: [[832, 128], [3, 637]]

[Verifier binary @ thr=0.7] acc=0.944  prec=0.880  rec=0.995  f1=0.934  roc=0.9934488932291666  pr_auc=0.9825779645323546
  CM: [[873, 87], [3, 637]]

[Official SemEval-like metrics]
  mean_score: 0.7775
  exact_rate: 0.715
  partial_rate: 0.125
  zero_rate: 0.16
  avg_pred_labels: 1.585
  none_rate: 0.15
  total_fp: 74
  total_fn: 80

In [38]:
import os
from google.colab import files

output_zip = "output_folder.zip"
!zip -rq {output_zip} {OUT_DIR}
files.download(output_zip)
print("Download triggered.")

Download triggered.

In [39]:
import numpy as np
import json, os, math
from collections import defaultdict, Counter
from sklearn.metrics import (
    accuracy_score, precision_recall_fscore_support,
    roc_auc_score, average_precision_score,
    confusion_matrix, classification_report,
    brier_score_loss
)
from sklearn.calibration import calibration_curve
from sklearn.metrics import roc_curve, precision_recall_curve
from scipy import stats as scipy_stats
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

PLOT_DIR = os.path.join(OUT_DIR, "analysis_plots")
os.makedirs(PLOT_DIR, exist_ok=True)

dev_rows  = result_single["dev_rows"]
dev_probs = result_single["dev_probs"]
qid_probs = result_single["qid_probs"]
Th, Tl, rr = result_single["decode"]

y_true = np.array([int(r["label"]) for r in dev_rows], dtype=np.int64)
y_prob = dev_probs

print("Analysis setup done.")
print(f"Dev rows: {len(dev_rows)}  Positives: {y_true.sum()}  Negatives: {(y_true==0).sum()}")

Analysis setup done.
Dev rows: 1600  Positives: 640  Negatives: 960

In [40]:
print("1. VERIFIER BINARY CLASSIFICATION REPORT")

for thr in [0.3, 0.4, 0.5, 0.6, 0.7]:
    y_pred = (y_prob >= thr).astype(np.int64)
    acc  = accuracy_score(y_true, y_pred)
    p, r, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="binary", zero_division=0)
    print(f"  thr={thr:.1f}  acc={acc:.4f}  prec={p:.4f}  rec={r:.4f}  f1={f1:.4f}")

best_f1, best_thr = 0, 0.5
for thr in np.linspace(0.1, 0.9, 81):
    y_pred = (y_prob >= thr).astype(np.int64)
    _, _, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="binary", zero_division=0)
    if f1 > best_f1:
        best_f1, best_thr = f1, thr

print(f"\n  Best F1 = {best_f1:.4f}  at threshold = {best_thr:.3f}")

roc_auc = roc_auc_score(y_true, y_prob)
pr_auc  = average_precision_score(y_true, y_prob)
brier   = brier_score_loss(y_true, y_prob)
print(f"  ROC-AUC  = {roc_auc:.4f}")
print(f"  PR-AUC   = {pr_auc:.4f}")
print(f"  Brier    = {brier:.4f}  (lower=better)")

y_pred_best = (y_prob >= best_thr).astype(np.int64)
print(f"\n  Classification Report @ thr={best_thr:.3f}:")
print(classification_report(y_true, y_pred_best,
      target_names=["NON-CAUSE", "CAUSE"], zero_division=0))

cm = confusion_matrix(y_true, y_pred_best)
tn, fp, fn, tp = cm.ravel()
print(f"  Confusion Matrix: TN={tn}  FP={fp}  FN={fn}  TP={tp}")
print(f"  FPR = {fp/(fp+tn):.4f}  (non-causes predicted as causes)")
print(f"  FNR = {fn/(fn+tp):.4f}  (causes missed)")

1. VERIFIER BINARY CLASSIFICATION REPORT
  thr=0.3  acc=0.8769  prec=0.7646  rec=1.0000  f1=0.8666
  thr=0.4  acc=0.8988  prec=0.8003  rec=0.9953  f1=0.8872
  thr=0.5  acc=0.9181  prec=0.8327  rec=0.9953  f1=0.9068
  thr=0.6  acc=0.9319  prec=0.8573  rec=0.9953  f1=0.9212
  thr=0.7  acc=0.9437  prec=0.8798  rec=0.9953  f1=0.9340

  Best F1 = 0.9574  at threshold = 0.900
  ROC-AUC  = 0.9934
  PR-AUC   = 0.9826
  Brier    = 0.0645  (lower=better)

  Classification Report @ thr=0.900:
              precision    recall  f1-score   support

   NON-CAUSE       0.99      0.95      0.97       960
       CAUSE       0.93      0.98      0.96       640

    accuracy                           0.96      1600
   macro avg       0.96      0.97      0.96      1600
weighted avg       0.97      0.96      0.97      1600

  Confusion Matrix: TN=915  FP=45  FN=11  TP=629
  FPR = 0.0469  (non-causes predicted as causes)
  FNR = 0.0172  (causes missed)

In [41]:
print("2. SEMEVAL TASK-LEVEL METRICS")
per_ex_scores = []
gold_sizes, pred_sizes_list = [], []
fp_total = fn_total = 0
none_predictions = correct_none = wrong_none = 0

for ex in dev_data:
    qid      = ex["id"]
    none_key = find_none_key(ex["options"])
    pred     = decode_conservative(qid_probs[qid], none_key, Th, Tl, rr)
    sc       = semeval_score(ex["gold"], pred)
    per_ex_scores.append(sc)

    G = set(parse_gold(ex["gold"]))
    P = set(parse_gold(pred))
    gold_sizes.append(len(G))
    pred_sizes_list.append(len(P))

    if none_key and P == {none_key}:
        none_predictions += 1
        if G == {none_key}: correct_none += 1
        else: wrong_none += 1

    fp_total += len(P - G)
    fn_total += len(G - P)

scores_arr = np.array(per_ex_scores)
exact   = (scores_arr == 1.0).sum()
partial = (scores_arr == 0.5).sum()
zero    = (scores_arr == 0.0).sum()
N       = len(dev_data)

print(f"\nMean Score : {scores_arr.mean():.4f}  ±{scores_arr.std():.4f}")
print(f"\nMedian Score : {np.median(scores_arr):.4f}")
print(f"\nExact Match : {exact}/{N} = {exact/N:.4f}")
print(f"\nPartial Match : {partial}/{N} = {partial/N:.4f}")
print(f"\nZero Score : {zero}/{N} = {zero/N:.4f}")
print(f"\nNone predicted : {none_predictions}  (correct={correct_none}, wrong={wrong_none})")
print(f"\nFalse Positives: {fp_total}  False Negatives: {fn_total}")
print(f"\nAvg gold labels: {np.mean(gold_sizes):.2f}  Avg pred labels: {np.mean(pred_sizes_list):.2f}")

print(f"\nScore by gold answer cardinality:")
for g_size in sorted(set(gold_sizes)):
    idxs = [i for i, g in enumerate(gold_sizes) if g == g_size]
    sc_sub = scores_arr[idxs]
    print(f"    |gold|={g_size}: n={len(idxs):4d}  mean={sc_sub.mean():.4f}"
          f"  exact={(sc_sub==1).mean():.4f}  zero={(sc_sub==0).mean():.4f}")

2. SEMEVAL TASK-LEVEL METRICS

Mean Score : 0.7775  ±0.3765

Median Score : 1.0000

Exact Match : 286/400 = 0.7150

Partial Match : 50/400 = 0.1250

Zero Score : 64/400 = 0.1600

None predicted : 18  (correct=18, wrong=0)

False Positives: 74  False Negatives: 80

Avg gold labels: 1.60  Avg pred labels: 1.58

Score by gold answer cardinality:
    |gold|=1: n= 210  mean=0.6952  exact=0.6952  zero=0.3048
    |gold|=2: n= 140  mean=1.0000  exact=1.0000  zero=0.0000
    |gold|=3: n=  50  mean=0.5000  exact=0.0000  zero=0.0000

In [42]:
print("3. CONFIDENCE CALIBRATION ANALYSIS")
n_bins = 10
bin_edges = np.linspace(0, 1, n_bins + 1)
ece = 0.0
bin_stats = []
for i in range(n_bins):
    lo, hi = bin_edges[i], bin_edges[i+1]
    mask = (y_prob >= lo) & (y_prob < hi)
    if mask.sum() == 0:
        bin_stats.append(None)
        continue
    avg_conf = y_prob[mask].mean()
    avg_acc  = y_true[mask].mean()
    frac     = mask.sum() / len(y_prob)
    ece     += frac * abs(avg_conf - avg_acc)
    bin_stats.append((lo, hi, avg_conf, avg_acc, int(mask.sum())))

print(f"ECE = {ece:.4f}  (lower=better)")
print(f"Brier Score = {brier:.4f}")
print(f"\n  Calibration bins (avg_conf vs avg_acc):")
for bs in bin_stats:
    if bs is None: continue
    lo, hi, ac, aa, n = bs
    gap = abs(ac - aa)
    bar = "█" * int(ac * 20)
    print(f"    [{lo:.1f}-{hi:.1f}]  conf={ac:.3f}  acc={aa:.3f}  gap={gap:.3f}  n={n:4d}  {bar}")

3. CONFIDENCE CALIBRATION ANALYSIS
ECE = 0.1096  (lower=better)
Brier Score = 0.0645

  Calibration bins (avg_conf vs avg_acc):
    [0.0-0.1]  conf=0.052  acc=0.000  gap=0.052  n= 563  █
    [0.1-0.2]  conf=0.135  acc=0.000  gap=0.135  n= 137  ██
    [0.2-0.3]  conf=0.236  acc=0.000  gap=0.236  n=  63  ████
    [0.3-0.4]  conf=0.348  acc=0.073  gap=0.274  n=  41  ██████
    [0.4-0.5]  conf=0.441  acc=0.000  gap=0.441  n=  31  ████████
    [0.5-0.6]  conf=0.540  acc=0.000  gap=0.540  n=  22  ██████████
    [0.6-0.7]  conf=0.659  acc=0.000  gap=0.659  n=  19  █████████████
    [0.7-0.8]  conf=0.757  acc=0.000  gap=0.757  n=  19  ███████████████
    [0.8-0.9]  conf=0.868  acc=0.258  gap=0.610  n=  31  █████████████████
    [0.9-1.0]  conf=0.978  acc=0.933  gap=0.045  n= 674  ███████████████████

In [43]:
print("4. ERROR ANALYSIS")
nli_by_label = defaultdict(lambda: {"correct": 0, "total": 0})
dir_by_label = defaultdict(lambda: {"correct": 0, "total": 0})

for r, prob in zip(dev_rows, y_prob):
    pred_label = 1 if prob >= best_thr else 0
    correct    = int(pred_label == r["label"])
    nli_by_label[r["nli_tag"]]["total"]   += 1
    nli_by_label[r["nli_tag"]]["correct"] += correct
    dir_by_label[r["dir_hint"]]["total"]   += 1
    dir_by_label[r["dir_hint"]]["correct"] += correct

print("  Accuracy by NLI signal tag:")
for tag, d in sorted(nli_by_label.items()):
    acc = d["correct"] / d["total"] if d["total"] else 0
    print(f"    {tag:15s}: acc={acc:.4f}  n={d['total']}")

print("\n  Accuracy by direction hint:")
for tag, d in sorted(dir_by_label.items()):
    acc = d["correct"] / d["total"] if d["total"] else 0
    print(f"    {tag:25s}: acc={acc:.4f}  n={d['total']}")

y_pred_best = (y_prob >= best_thr).astype(np.int64)
tp_probs = y_prob[(y_true==1) & (y_pred_best==1)]
fp_probs = y_prob[(y_true==0) & (y_pred_best==1)]
fn_probs = y_prob[(y_true==1) & (y_pred_best==0)]
tn_probs = y_prob[(y_true==0) & (y_pred_best==0)]

print(f"\n  Probability distributions (mean ± std):")
print(f"TP (n={len(tp_probs):4d}): {tp_probs.mean():.4f} ± {tp_probs.std():.4f}")
print(f"FP (n={len(fp_probs):4d}): {fp_probs.mean():.4f} ± {fp_probs.std():.4f}")
print(f"FN (n={len(fn_probs):4d}): {fn_probs.mean():.4f} ± {fn_probs.std():.4f}")
print(f"TN (n={len(tn_probs):4d}): {tn_probs.mean():.4f} ± {tn_probs.std():.4f}")

t_stat, p_val = scipy_stats.ttest_ind(
    y_prob[y_true==1], y_prob[y_true==0])
print(f"\nt-test (pos vs neg probs): t={t_stat:.3f}  p={p_val:.6f}")

print(f"\nTop-10 hardest positives (gold=1, lowest predicted prob):")
pos_rows = [(r, p) for r, p in zip(dev_rows, y_prob) if r["label"]==1]
pos_rows.sort(key=lambda x: x[1])
for r, p in pos_rows[:10]:
    print(f"    prob={p:.4f}  nli={r['nli_tag']:12s}  "
          f"dir={r['dir_hint']:20s}  opt={r['option_key']}")

4. ERROR ANALYSIS
  Accuracy by NLI signal tag:
    CONTRADICTS    : acc=0.9779  n=181
    ENTAILS        : acc=0.9277  n=166
    NEUTRAL        : acc=0.9681  n=1253

  Accuracy by direction hint:
    EVENT_BEFORE_OPT         : acc=0.9694  n=914
    OPT_BEFORE_EVENT         : acc=0.9377  n=273
    UNCLEAR                  : acc=0.9734  n=413

  Probability distributions (mean ± std):
TP (n= 629): 0.9806 ± 0.0101
FP (n=  45): 0.9452 ± 0.0241
FN (n=  11): 0.7370 ± 0.2280
TN (n= 915): 0.1617 ± 0.2023

t-test (pos vs neg probs): t=75.533  p=0.000000

Top-10 hardest positives (gold=1, lowest predicted prob):
    prob=0.3519  nli=NEUTRAL       dir=UNCLEAR               opt=A
    prob=0.3715  nli=ENTAILS       dir=UNCLEAR               opt=A
    prob=0.3715  nli=ENTAILS       dir=UNCLEAR               opt=B
    prob=0.8665  nli=CONTRADICTS   dir=EVENT_BEFORE_OPT      opt=D
    prob=0.8665  nli=CONTRADICTS   dir=EVENT_BEFORE_OPT      opt=D
    prob=0.8728  nli=NEUTRAL       dir=OPT_BEFORE_EVENT      opt=A
    prob=0.8728  nli=NEUTRAL       dir=OPT_BEFORE_EVENT      opt=A
    prob=0.8753  nli=CONTRADICTS   dir=OPT_BEFORE_EVENT      opt=B
    prob=0.8753  nli=CONTRADICTS   dir=OPT_BEFORE_EVENT      opt=C
    prob=0.8917  nli=NEUTRAL       dir=UNCLEAR               opt=A

In [44]:
print("5. DECODE THRESHOLD SENSITIVITY")
print(f"Optimal: Th={Th:.3f}  Tl={Tl:.3f}  ratio={rr:.3f}")
print(f"\n  Sweeping T_high (Tl={Tl:.3f}, ratio={rr:.3f} fixed):")

for th_test in np.linspace(0.3, 0.95, 14):
    st = eval_dev(dev_data, qid_probs, float(th_test), float(Tl), float(rr))
    bar = "█" * int(st["mean_score"] * 40)
    print(f"  Th={th_test:.2f}  score={st['mean_score']:.4f}  "
          f"exact={st['exact_rate']:.3f}  "
          f"none={st['none_rate']:.3f}  {bar}")

5. DECODE THRESHOLD SENSITIVITY
Optimal: Th=0.391  Tl=0.200  ratio=0.750

  Sweeping T_high (Tl=0.200, ratio=0.750 fixed):
  Th=0.30  score=0.7750  exact=0.713  none=0.147  ███████████████████████████████
  Th=0.35  score=0.7750  exact=0.713  none=0.147  ███████████████████████████████
  Th=0.40  score=0.7775  exact=0.715  none=0.150  ███████████████████████████████
  Th=0.45  score=0.7850  exact=0.723  none=0.158  ███████████████████████████████
  Th=0.50  score=0.7875  exact=0.725  none=0.160  ███████████████████████████████
  Th=0.55  score=0.7950  exact=0.733  none=0.170  ███████████████████████████████
  Th=0.60  score=0.7975  exact=0.735  none=0.172  ███████████████████████████████
  Th=0.65  score=0.8050  exact=0.743  none=0.180  ████████████████████████████████
  Th=0.70  score=0.8075  exact=0.745  none=0.182  ████████████████████████████████
  Th=0.75  score=0.8100  exact=0.748  none=0.185  ████████████████████████████████
  Th=0.80  score=0.8125  exact=0.750  none=0.188  ████████████████████████████████
  Th=0.85  score=0.8125  exact=0.750  none=0.188  ████████████████████████████████
  Th=0.90  score=0.8150  exact=0.752  none=0.203  ████████████████████████████████
  Th=0.95  score=0.8163  exact=0.752  none=0.233  ████████████████████████████████

In [45]:
print("6. CEG EVIDENCE QUALITY ANALYSIS")
ev_lens = [len(r["evidence"]) for r in dev_rows]
ev_lens_pos = [len(r["evidence"]) for r in dev_rows if r["label"]==1]
ev_lens_neg = [len(r["evidence"]) for r in dev_rows if r["label"]==0]

print(f"\nEvidence length (chars):")
print(f"\nAll: mean={np.mean(ev_lens):.1f}  std={np.std(ev_lens):.1f}  "
      f"min={np.min(ev_lens)}  max={np.max(ev_lens)}")
print(f"\nPositive: mean={np.mean(ev_lens_pos):.1f}  std={np.std(ev_lens_pos):.1f}")
print(f"\nNegative: mean={np.mean(ev_lens_neg):.1f}  std={np.std(ev_lens_neg):.1f}")

t_stat, p_val = scipy_stats.ttest_ind(ev_lens_pos, ev_lens_neg)
print(f"  t-test (pos vs neg evidence length): t={t_stat:.3f}  p={p_val:.4f}")

nli_dist = Counter(r["nli_tag"]  for r in dev_rows)
dir_dist = Counter(r["dir_hint"] for r in dev_rows)
nli_gold = Counter(r["nli_tag"]  for r in dev_rows if r["label"]==1)
nli_neg  = Counter(r["nli_tag"]  for r in dev_rows if r["label"]==0)

print(f"\nNLI tag distribution (all): {dict(nli_dist)}")
print(f"\nDir hint distribution (all): {dict(dir_dist)}")
print(f"\nNLI tags — GOLD options: {dict(nli_gold)}")
print(f"\nNLI tags — NON-GOLD options: {dict(nli_neg)}")

6. CEG EVIDENCE QUALITY ANALYSIS

Evidence length (chars):

All: mean=2587.0  std=351.2  min=723  max=2999

Positive: mean=2643.1  std=290.3

Negative: mean=2549.7  std=382.0
  t-test (pos vs neg evidence length): t=5.253  p=0.0000

NLI tag distribution (all): {'CONTRADICTS': 181, 'NEUTRAL': 1253, 'ENTAILS': 166}

Dir hint distribution (all): {'EVENT_BEFORE_OPT': 914, 'UNCLEAR': 413, 'OPT_BEFORE_EVENT': 273}

NLI tags — GOLD options: {'NEUTRAL': 488, 'ENTAILS': 95, 'CONTRADICTS': 57}

NLI tags — NON-GOLD options: {'CONTRADICTS': 124, 'NEUTRAL': 765, 'ENTAILS': 71}

In [46]:
print("7. BOOTSTRAP CONFIDENCE INTERVALS  (n=1000)")

n_boot = 1000

boot_scores = []
for _ in range(n_boot):
    idxs = np.random.choice(len(per_ex_scores), len(per_ex_scores), replace=True)
    boot_scores.append(np.mean([per_ex_scores[i] for i in idxs]))
boot_scores = np.array(boot_scores)
ci_lo, ci_hi = np.percentile(boot_scores, [2.5, 97.5])
print(f"\nMean Score : {scores_arr.mean():.4f}  95% CI: [{ci_lo:.4f}, {ci_hi:.4f}]")

boot_roc = []
for _ in range(n_boot):
    idxs = np.random.choice(len(y_true), len(y_true), replace=True)
    yt, yp = y_true[idxs], y_prob[idxs]
    if len(np.unique(yt)) == 2:
        boot_roc.append(roc_auc_score(yt, yp))
boot_roc = np.array(boot_roc)
roc_lo, roc_hi = np.percentile(boot_roc, [2.5, 97.5])
print(f"\nROC-AUC : {roc_auc:.4f}  95% CI: [{roc_lo:.4f}, {roc_hi:.4f}]")

boot_f1 = []
for _ in range(n_boot):
    idxs = np.random.choice(len(y_true), len(y_true), replace=True)
    yt = y_true[idxs]
    yp = (y_prob[idxs] >= best_thr).astype(np.int64)
    _, _, f1_b, _ = precision_recall_fscore_support(
        yt, yp, average="binary", zero_division=0)
    boot_f1.append(f1_b)
boot_f1 = np.array(boot_f1)
f1_lo, f1_hi = np.percentile(boot_f1, [2.5, 97.5])
print(f"\nBest F1 : {best_f1:.4f}  95% CI: [{f1_lo:.4f}, {f1_hi:.4f}]")

7. BOOTSTRAP CONFIDENCE INTERVALS  (n=1000)

Mean Score : 0.7775  95% CI: [0.7412, 0.8163]

ROC-AUC : 0.9934  95% CI: [0.9893, 0.9968]

Best F1 : 0.9574  95% CI: [0.9463, 0.9677]

In [47]:
print("Generating analysis dashboard...")

fig = plt.figure(figsize=(20, 16))
gs  = gridspec.GridSpec(3, 3, figure=fig, hspace=0.45, wspace=0.35)

# 1 — Score distribution
ax1 = fig.add_subplot(gs[0, 0])
ax1.bar(["Exact\n(1.0)", "Partial\n(0.5)", "Zero\n(0.0)"],
        [exact/N, partial/N, zero/N],
        color=["#2ecc71", "#f39c12", "#e74c3c"], edgecolor="black", width=0.5)
ax1.set_title("Score Distribution", fontweight="bold")
ax1.set_ylabel("Fraction")
for i, v in enumerate([exact/N, partial/N, zero/N]):
    ax1.text(i, v + 0.005, f"{v:.3f}", ha="center", fontsize=10)

# 2 — Calibration curve
ax2 = fig.add_subplot(gs[0, 1])
frac_pos, mean_pred = calibration_curve(y_true, y_prob, n_bins=10, strategy="uniform")
ax2.plot(mean_pred, frac_pos, "o-", color="#3498db", label="Model", linewidth=2)
ax2.plot([0,1],[0,1], "k--", alpha=0.5, label="Perfect")
ax2.fill_between(mean_pred, frac_pos, mean_pred, alpha=0.15, color="#e74c3c")
ax2.set_xlabel("Mean Predicted Prob")
ax2.set_ylabel("Fraction Positives")
ax2.set_title(f"Calibration Curve\nECE={ece:.4f}", fontweight="bold")
ax2.legend(); ax2.grid(alpha=0.3)

# 3 — Prob histogram by outcome
ax3 = fig.add_subplot(gs[0, 2])
bins = np.linspace(0, 1, 25)
ax3.hist(tp_probs, bins=bins, alpha=0.6, color="#2ecc71", label=f"TP(n={len(tp_probs)})", density=True)
ax3.hist(fp_probs, bins=bins, alpha=0.6, color="#e74c3c", label=f"FP(n={len(fp_probs)})", density=True)
ax3.hist(fn_probs, bins=bins, alpha=0.6, color="#e67e22", label=f"FN(n={len(fn_probs)})", density=True)
ax3.hist(tn_probs, bins=bins, alpha=0.4, color="#95a5a6", label=f"TN(n={len(tn_probs)})", density=True)
ax3.axvline(best_thr, color="black", linestyle="--", label=f"thr={best_thr:.2f}")
ax3.set_xlabel("Predicted Probability")
ax3.set_ylabel("Density")
ax3.set_title("Prob Distribution by Outcome", fontweight="bold")
ax3.legend(fontsize=8); ax3.grid(alpha=0.3)

# 4 — ROC curve
ax4 = fig.add_subplot(gs[1, 0])
fpr_arr, tpr_arr, _ = roc_curve(y_true, y_prob)
ax4.plot(fpr_arr, tpr_arr, color="#3498db", linewidth=2, label=f"AUC={roc_auc:.4f}")
ax4.fill_between(fpr_arr, tpr_arr, alpha=0.1, color="#3498db")
ax4.plot([0,1],[0,1], "k--", alpha=0.5)
ax4.set_xlabel("FPR"); ax4.set_ylabel("TPR")
ax4.set_title("ROC Curve", fontweight="bold")
ax4.legend(); ax4.grid(alpha=0.3)

# 5 — PR curve
ax5 = fig.add_subplot(gs[1, 1])
prec_arr, rec_arr, _ = precision_recall_curve(y_true, y_prob)
ax5.plot(rec_arr, prec_arr, color="#9b59b6", linewidth=2, label=f"AP={pr_auc:.4f}")
ax5.fill_between(rec_arr, prec_arr, alpha=0.1, color="#9b59b6")
ax5.set_xlabel("Recall"); ax5.set_ylabel("Precision")
ax5.set_title("Precision-Recall Curve", fontweight="bold")
ax5.legend(); ax5.grid(alpha=0.3)

# 6 — Threshold sensitivity
ax6 = fig.add_subplot(gs[1, 2])
th_vals     = np.linspace(0.2, 0.95, 30)
task_scores = [eval_dev(dev_data, qid_probs, float(th), float(Tl), float(rr))["mean_score"] for th in th_vals]
none_rates  = [eval_dev(dev_data, qid_probs, float(th), float(Tl), float(rr))["none_rate"]  for th in th_vals]
ax6.plot(th_vals, task_scores, "o-", color="#2ecc71", linewidth=2, label="Mean Score")
ax6b = ax6.twinx()
ax6b.plot(th_vals, none_rates, "s--", color="#e74c3c", linewidth=1.5, label="None Rate")
ax6.axvline(Th, color="black", linestyle=":", label=f"Optimal Th={Th:.2f}")
ax6.set_xlabel("T_high")
ax6.set_ylabel("Mean Score", color="#2ecc71")
ax6b.set_ylabel("None Rate", color="#e74c3c")
ax6.set_title("Threshold Sensitivity", fontweight="bold")
ax6.grid(alpha=0.3)

# 7 — Bootstrap CI histogram
ax7 = fig.add_subplot(gs[2, 0])
ax7.hist(boot_scores, bins=40, color="#3498db", edgecolor="white", alpha=0.8)
ax7.axvline(scores_arr.mean(), color="#e74c3c", linewidth=2, label=f"Mean={scores_arr.mean():.4f}")
ax7.axvline(ci_lo, color="orange", linestyle="--", linewidth=1.5, label=f"95% CI")
ax7.axvline(ci_hi, color="orange", linestyle="--", linewidth=1.5)
ax7.set_xlabel("Bootstrap Mean Score")
ax7.set_ylabel("Count")
ax7.set_title("Bootstrap CI — Task Score", fontweight="bold")
ax7.legend(fontsize=9); ax7.grid(alpha=0.3)

# 8 — NLI tag accuracy
ax8 = fig.add_subplot(gs[2, 1])
nli_tags = list(nli_by_label.keys())
nli_accs = [nli_by_label[t]["correct"]/nli_by_label[t]["total"] for t in nli_tags]
nli_ns   = [nli_by_label[t]["total"] for t in nli_tags]
colors_nli = ["#2ecc71" if "ENT" in t else "#e74c3c" if "CONT" in t else "#95a5a6" for t in nli_tags]
bars = ax8.bar(nli_tags, nli_accs, color=colors_nli, edgecolor="black")
for bar, n in zip(bars, nli_ns):
    ax8.text(bar.get_x() + bar.get_width()/2,
             bar.get_height() + 0.01, f"n={n}", ha="center", fontsize=9)
ax8.set_ylim(0, 1.15)
ax8.set_ylabel("Accuracy")
ax8.set_title("Accuracy by NLI Signal", fontweight="bold")
ax8.grid(axis="y", alpha=0.3)

# 9 — Score by gold cardinality
ax9 = fig.add_subplot(gs[2, 2])
g_sizes = sorted(set(gold_sizes))
g_means = [scores_arr[[i for i,g in enumerate(gold_sizes) if g==gs_]].mean() for gs_ in g_sizes]
g_ns    = [sum(1 for g in gold_sizes if g==gs_) for gs_ in g_sizes]
ax9.bar([str(g) for g in g_sizes], g_means,
        color=["#3498db","#9b59b6","#e67e22"][:len(g_sizes)], edgecolor="black")
for i, (m, n) in enumerate(zip(g_means, g_ns)):
    ax9.text(i, m + 0.01, f"{m:.3f}\nn={n}", ha="center", fontsize=9)
ax9.set_xlabel("Number of Gold Answers")
ax9.set_ylabel("Mean Score")
ax9.set_title("Score by Answer Cardinality", fontweight="bold")
ax9.set_ylim(0, 1.15); ax9.grid(axis="y", alpha=0.3)

plt.suptitle("AER System — Research-Grade Analysis Dashboard",
             fontsize=15, fontweight="bold", y=1.01)
plot_path = os.path.join(PLOT_DIR, "analysis_dashboard.png")
plt.savefig(plot_path, dpi=150, bbox_inches="tight")
plt.close()
print(f"Saved: {plot_path}")

Generating analysis dashboard...
Saved: /content/output/analysis_plots/analysis_dashboard.png

In [48]:
print("PAPER-READY SUMMARY TABLE")
print(f"\n{'Metric':<32} {'Value':>8}  {'95% CI'}")
print(f"\n{'-'*58}")
print(f"\n{'Task Mean Score':<32} {scores_arr.mean():>8.4f}  [{ci_lo:.4f}, {ci_hi:.4f}]")
print(f"\n{'Exact Match Rate':<32} {exact/N:>8.4f}")
print(f"\n{'Partial Match Rate':<32} {partial/N:>8.4f}")
print(f"\n{'Zero Score Rate':<32} {zero/N:>8.4f}")
print(f"\n{'Verifier ROC-AUC':<32} {roc_auc:>8.4f}  [{roc_lo:.4f}, {roc_hi:.4f}]")
print(f"\n{'Verifier PR-AUC':<32} {pr_auc:>8.4f}")
print(f"\n{'Verifier Best F1':<32} {best_f1:>8.4f}  [{f1_lo:.4f}, {f1_hi:.4f}]")
print(f"\n{'Brier Score':<32} {brier:>8.4f}")
print(f"\n{'ECE':<32} {ece:>8.4f}")
print(f"\n{'Optimal T_high':<32} {Th:>8.3f}")
print(f"\n{'Optimal T_low':<32} {Tl:>8.3f}")
print(f"\n{'Optimal ratio':<32} {rr:>8.3f}")
print(f"\n{'None Rate':<32} {none_predictions/N:>8.4f}")
print(f"\n{'Total FP':<32} {fp_total:>8d}")
print(f"\n{'Total FN':<32} {fn_total:>8d}")
print(f"\nPlots saved to: {PLOT_DIR}")

PAPER-READY SUMMARY TABLE

Metric                              Value  95% CI

----------------------------------------------------------

Task Mean Score                    0.7775  [0.7412, 0.8163]

Exact Match Rate                   0.7150

Partial Match Rate                 0.1250

Zero Score Rate                    0.1600

Verifier ROC-AUC                   0.9934  [0.9893, 0.9968]

Verifier PR-AUC                    0.9826

Verifier Best F1                   0.9574  [0.9463, 0.9677]

Brier Score                        0.0645

ECE                                0.1096

Optimal T_high                      0.391

Optimal T_low                       0.200

Optimal ratio                       0.750

None Rate                          0.0450

Total FP                               74

Total FN                               80

Plots saved to: /content/output/analysis_plots